name: flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  sensors_plus: ^5.0.1
  shared_preferences: ^2.2.3
  soundpool: ^2.4.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cat.jpeg
    - assets/do1.wav
    - assets/re.wav
    - assets/mi.wav
    - assets/fa.wav
    - assets/sol.wav
    - assets/la.wav
    - assets/si.wav
 
